import React, { useEffect, useState, useRef } from "react";
import chart1 from "../../images/comcast_census_blocks_2022-02-18_3pm.png";
import chart2 from "../../images/residential_fiber_blocks.png";
import ImageModal from "../modules/imageModal";

const Infrastructure = () => {

  return (
    <div>
      <div className="section section-bottom">
        <p>Complicating the question of coverage, Form 477 is self-reported by providers and does not include levels of service offered. Providers are only asked to report the highest levels of speed (mbps download and upload) serviced provided infor each census block. What is not reported is the different service level available at what cost. While the FCC is working to implement “Broadband Nutrition Labels”, today clearcurrent comparisons ofinformation about viability speed and cost between providers is limited to the form 477 data. Only the ISPs know the dDetails of what addresses are served, not served, or where the infrastructure is; this level of detail  known only by the individual ISPs and not reported to the FCC, nor regularly reported through other state or local requirements. (SEE RECOMMENDATION: XX Data Reporting)</p>
        <p>Form 477 data does can in part start to illustrate who are the major available providers, and what technology is prevalent in the a given area. The table below lists providers from the FCC data. Comcast, RCN, Starry, and NetBlazr each service some portion of Everett, Chelsea and/or Revere. There are a limited number of providers in the area who can provide 100/10 speeds. Those that can provide those speeds, use a mix of fiber, fixed wireless, and cable technologies.</p>
        <iframe src="https://public.tableau.com/views/FCC_DA_Munis/TechnologyTableDashboard?:showVizHome=no&:embed=true" width="100%" height="650"></iframe>
        <p>The Form 477 data is mapped below, where the color indicates the number of ISPs that report serving that census block. Many census blocks have 2 provider options, and the darkest colored areas have all 4 of these residential provider options available in the census block. It’s worth mentioning again that a provider reporting via Form 477 that it serves a given census block is no guarantee that all residents have or could even subscribe to that provider.  While business may have additional ISP options residents across these three communities don’t have the same level of choice nor competition.</p>
        <iframe src="https://mapc.github.io/fcc-map/" width="100%" height="600"></iframe>
        <p>Looking closer at the technologies used in the map below, there are less fewer than 20 census blocks where the service connection allows a direct connection to the internet via fiber optic lines from any one of the providers. that the 4 area residential providers report having fiber connections within them. This doesn’t mean that there’s no fiber: This map and data does not mean these residential providers (Comcast, RCN, Starry, netBlazr)b do not utilize fiber in these communities. What it does show is that both Comcast and RCN networks have hybrid fiber/coaxial networks in these communities, but nearly every connection will rely in part on still report relying on some coaxial / cable technology (listed as DOCSIS 3.0 /3.1 systems) between the home and the internet across their full area of services. While these ISP have hybrid fiber/coaxial networks, no blocks are reported as being served solely by fiber, highlighting that aA full fiber to the home network, replacing the slower coaxial lines, would require significant investment to achieve given the current state.</p>
        <p>Alongside the public infrastructure of sewer, water, and roads in Everett, Chelsea, and Revere private companies have run many miles of cables underneath city streets and poles, providing a connection to the internet. Unlike rural areas in Massachusetts and across the United States, there exists relatively more wiring in these urban areas to connect residents and businesses to the internet. This can be attributed in large part to the market forces driving this private installation of wiring. The desire to connect large amounts of customers as efficiently as possible. Large dense urban areas provide more potential customers per mile of investment.</p>
        <p>However, as we have seen in the access and service & affordability sections of this report, having wiring on your street does not mean you are able to connect of leverage that infrastructure. The type of wiring is also critical when discussing the investment, we collectively need to make to connect residents and businesses in the future. Speed needed in future reference. Moore’s law for speed </p>
        <p>As the Journey through the Internet slides highlighted fiber-optic wiring provides a dramatic and generational advancement as compared to copper coaxial cables that replaced the prior copper telephone wiring. To understand how much of the wiring running under the streets of these communities was fiber as compared to copper, Everett, Chelsea, and Revere leveraged their Cable Franchise agreements to obtain line level data that identified the network of fiber and coaxial of the two major residential providers Comcast and RCN. In addition, MAPC also purchased commercial provider data from GeoTel to reference and help fill out the picture of wiring running under the streets of these communities. </p>
        <p>Looking just at Comcast and RCN networks coaxial wiring is the dominant wiring technology in place in the communities today. Copper coaxial wiring lines the telephone poles and it also today plays a critical role at and inside the home/dwelling. The wiring cable companies helped install in homes over past decades and provided them with a competitive market advantage (over telecom) when it was discovered that the same coaxial cable technology could be leveraged for internet services in addition to cable tv service, is also today a limiting factor in providing faster and more advanced services (need referenced / clear examples here like HD video streaming, teleconferencing, gaming etc.). As coaxial technology can be relied on to provide speeds for the services plans available today (Avg plan in area?)in the hundreds of Mbps download. It is a limiting factor in the available download speeds. Symmetrical speeds of 100 over 100 are not easily or efficiently achieved with coaxial cable technology. While lab settings or incremental advancements can help improve the speeds to coaxial cable wiring, it’s physical properties do not compare with the ability and potential fiber-optic cables can provide. </p>
        <p>If we look at fiber lines Comcast and RCN leverage today in the communities there is significantly less  wiring than copper coaxial wiring. Using the propriety maps of Comcast and RCN, obtained through the cable franchise agreement, MAPC created this map that shows census blocks in all three communities that have fiber running with in them from these two providers. </p>
        <p>This map highlights that fiber lines are not ubiquitous in our three communities. As fiber comes to replace coaxial cabling throughout our cities and homes significant investment will be needed to accomplish this feat.  </p>
        <ImageModal
          source={chart1}
        />
        <p className="citation">A 200ft buffer was applied to the fiber lines. From that a percentage of coverage of census block track was calculated.</p>
        <p>Another look at the availability of fiber is to look at the FCC ISP self-reported data mentioned in the access section. This data highlights the census blocks, which at min could be just one building per block, that are connected with fiber. The map below shows for the 4 major residential providers in the communities and served Comcast, RCN, Starry and NetBlazer only Starry and NetBlazer report having any census blocks connected by fiber, and in total only 9 blocks are reported. </p>
        <ImageModal
          source={chart2} 
        />
        <p>While neighboring suburbs have more fiber to the home connection option available. Residents in these communities do not have that option available to them.  Verizon is one ISP with residential fiber options (FIOS) that does not report serving census blocks in Everett, Chelsea, Revere as they do in other parts of the MAPC region.</p>
        <p>While copper lines will cotinine to play a role as we look towards federal and private investment gear towards making infrastructure investments, including ARPA and IIJA, it is important to make investments in the technologies that will be needed to serve us all in 10, 20, 30 years down the line. Just as public investments in roads, sewers, and highways have generational lifespans, we are now at the similar   </p>
      </div>
      <div className="section section-bottom">
        <h4>Cable Franchise Agreements</h4>
        <p>As mentioned above fiber mapping is made possible through language in the Cable franchise agreements municipalities have with cable providers that operate service within a city. This is a critical touchpoint between municipal governments and private internet services providers and many of the same cable provider companies are internet service providers. (Call / bill reference to change DTC purview?)   It’s important to note that in addition to broadband internet service, Comcast, RCN, and Verizon often offer other media services such as cable television or phone service. As mentioned in the history section of this report, cable television service that had once been the primary offering has steadily seen residents in these communities “cut the cord” to cable television. Department of Television and Cable subscription numbers for these communities have steadily declined from 10,603 Comcast cable television subscribers in 2011 to 7,000 in 2020. RCN also saw significant loss in subscribes with a 56% drop in subscribes between the start of their cable television services in 2017 and 2020.</p>
      </div>
    </div>
  )
}

export default Infrastructure